<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: components\nav.latte */
final class Template_22eeb8c549 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<header class="shrink-0">
  <nav class="w-full flex flex-row items-center bg-';
		echo LR\HtmlHelpers::escapeAttr($theme) /* pos 30:52 */;
		echo '  justify-between px-4">
    <div>
    </div>
  <div class="text-xl font-semibold tracking-tight leading-none">
    EPub Viewer
  </div>
  <div >
        <sl-button
          id="theme-toggle"
          variant="success"
          size="medium"
          circle
          class=" text-black"
         
        >
        🌙
        </sl-button>
  </div>
</nav>


      </header>';
	}
}
