<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: layouts\base.latte */
final class Template_2d48a31f18 extends Latte\Runtime\Template
{
	public const Blocks = [
		['head' => 'blockHead', 'nav' => 'blockNav', 'content' => 'blockContent', 'scripts' => 'blockScripts'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<html lang="ja" data-theme="light" class="h-full sl-theme-light">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/css/main.css" />
    <script type="module" src="/shoelace/shoelace.es.js"></script>
    <script src="/js/main.js"></script>
';
		$this->renderBlock('head', get_defined_vars()) /* pos 8:5 */;
		echo '  </head>
  <body class="h-full m-0 overflow-hidden">
    <div class="h-full m-0 flex flex-col">
';
		$this->renderBlock('nav', get_defined_vars()) /* pos 12:17 */;
		echo '      <main class="w-full flex flex-1 overflow-hidden" style="border:1px solid red">
          <div class="w-full m-0 p-0 box-content mx-auto">
';
		$this->renderBlock('content', get_defined_vars()) /* pos 15:13 */;
		echo '          </div>
      </main>
      <!-- Footer -->
    </div>
';
		$this->renderBlock('scripts', get_defined_vars()) /* pos 23:5 */;
		echo '  </body>
</html>
';
	}


	/** {block head} on line 8 */
	public function blockHead(array $ʟ_args): void
	{
	}


	/** {block nav} on line 12 */
	public function blockNav(array $ʟ_args): void
	{
	}


	/** {block content} on line 15 */
	public function blockContent(array $ʟ_args): void
	{
	}


	/** {block scripts} on line 23 */
	public function blockScripts(array $ʟ_args): void
	{
	}
}
