<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: layouts\base.latte */
final class Template_2d48a31f18 extends Latte\Runtime\Template
{
	public const Blocks = [
		['head' => 'blockHead', 'nav' => 'blockNav', 'content' => 'blockContent', 'scripts' => 'blockScripts'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<html lang="ja" data-theme="light" class="sl-theme-light">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/css/main.css" />
    <script type="module" src="/shoelace/shoelace.es.js"></script>
    <script src="/js/main.js"></script>
';
		$this->renderBlock('head', get_defined_vars()) /* pos 8:5 */;
		echo '  </head>
  <body class="h-screen overflow-hidden">
    <div class="flex flex-col h-full">
';
		$this->renderBlock('nav', get_defined_vars()) /* pos 12:7 */;
		echo '      <main class="flex-1 min-h-0 overflow-y-auto">
';
		$this->renderBlock('content', get_defined_vars()) /* pos 14:9 */;
		echo '      </main>
    </div>
';
		$this->renderBlock('scripts', get_defined_vars()) /* pos 17:5 */;
		echo '  </body>
</html>
';
	}


	/** {block head} on line 8 */
	public function blockHead(array $ʟ_args): void
	{
	}


	/** {block nav} on line 12 */
	public function blockNav(array $ʟ_args): void
	{
	}


	/** {block content} on line 14 */
	public function blockContent(array $ʟ_args): void
	{
	}


	/** {block scripts} on line 17 */
	public function blockScripts(array $ʟ_args): void
	{
	}
}
