<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: pages/top.latte */
final class Template_356a25a05e extends Latte\Runtime\Template
{
	public const Blocks = [
		['head' => 'blockHead', 'nav' => 'blockNav', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('head', get_defined_vars()) /* pos 2:1 */;
		$this->renderBlock('nav', get_defined_vars()) /* pos 6:1 */;
		$this->renderBlock('content', get_defined_vars()) /* pos 9:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/base.latte';
		return get_defined_vars();
	}


	/** {block head} on line 2 */
	public function blockHead(array $ʟ_args): void
	{
		echo '  <link rel="stylesheet" href="pages/css/main.css" />
  <link rel="stylesheet" href="pages/css/mde.css" />
';
	}


	/** {block nav} on line 6 */
	public function blockNav(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->createTemplate('../components/nav.latte', ['theme' => 'success'] + $this->params, 'include')->renderToContentType('html') /* pos 7:3 */;
	}


	/** {block content} on line 9 */
	public function blockContent(array $ʟ_args): void
	{
		echo '<div class="h-screen flex flex-col">
  <!-- Heroセクション（画面上部のタイトル） -->
  <div class="hero p-6 text-center bg-success">
    <h1 class="text-3xl font-bold">メニュー</h1>
  </div>
  <!-- ボタン群（中央に配置） -->
  <div class="flex-1 flex flex-col items-center justify-center space-y-4 px-4">
    <sl-button variant="default" size="large" style="width: 50%;">新規作成</sl-button>
    <sl-button variant="default" size="large" style="width: 50%;">修正</sl-button>
    <sl-button variant="default" size="large" style="width: 50%;">閲覧</sl-button>
  </div>
</div>

';
	}
}
