<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: pages/image.latte */
final class Template_da86d7c2f2 extends Latte\Runtime\Template
{
	public const Blocks = [
		['head' => 'blockHead', 'nav' => 'blockNav', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('head', get_defined_vars()) /* pos 2:1 */;
		$this->renderBlock('nav', get_defined_vars()) /* pos 6:1 */;
		$this->renderBlock('content', get_defined_vars()) /* pos 9:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/base.latte';
		return get_defined_vars();
	}


	/** {block head} on line 2 */
	public function blockHead(array $ʟ_args): void
	{
		echo '  <link rel="stylesheet" href="pages/css/main.css" />
  <link rel="stylesheet" href="pages/css/mde.css" />
';
	}


	/** {block nav} on line 6 */
	public function blockNav(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->createTemplate('../components/nav.latte', ['theme' => 'success'] + $this->params, 'include')->renderToContentType('html') /* pos 7:3 */;
	}


	/** {block content} on line 9 */
	public function blockContent(array $ʟ_args): void
	{
		echo '
<div class="h-full rounded shadow flex flex-col min-h-0">

  <!-- TOOLBAR -->
  <div class="shadow flex gap-2 items-center p-2 shrink-0">

    <sl-button id="prevPage">&lt;</sl-button>
    <sl-button id="nextPage">&gt;</sl-button>
    <sl-button id="addSection">＋ Section</sl-button>
    <sl-button id="addRight">右寄せ図</sl-button>
    <sl-button id="addLeft">左寄せ図</sl-button>
    <sl-button id="togglePreview">Section Preview</sl-button>

    <button id="exportEpub"
      class="px-4 py-1 bg-purple-600 rounded text-white">
      Export EPUB3
    </button>

  </div>

     <div class="flex-1 min-h-0 flex p-2">
  <textarea
    id="editor"
    spellcheck="false"
    rows="20"
     class="w-full flex-1 overflow-y-auto leading-tight resize-none outline-none"
    style="box-sizing: content-box"
  ></textarea>
  <!-- PREVIEW -->
  <div
    id="preview"
    class="hidden flex-1 overflow-auto p-10 max-w-none"
  ></div>

</div>


</div>
<script type="module" src="/pages/js/mde.js"></script>
';
	}
}
