<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: pages/entry.latte */
final class Template_9cd1ccd157 extends Latte\Runtime\Template
{
	public const Blocks = [
		['head' => 'blockHead', 'nav' => 'blockNav', 'content' => 'blockContent', 'scripts' => 'blockScripts'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('head', get_defined_vars()) /* pos 2:1 */;
		$this->renderBlock('nav', get_defined_vars()) /* pos 6:1 */;
		$this->renderBlock('content', get_defined_vars()) /* pos 9:1 */;
		$this->renderBlock('scripts', get_defined_vars()) /* pos 31:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/base.latte';
		return get_defined_vars();
	}


	/** {block head} on line 2 */
	public function blockHead(array $ʟ_args): void
	{
		echo '  <link rel="stylesheet" href="pages/css/main.css" />
  <link rel="stylesheet" href="pages/css/mde.css" />
';
	}


	/** {block nav} on line 6 */
	public function blockNav(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->createTemplate('../components/nav.latte', ['theme' => 'success'] + $this->params, 'include')->renderToContentType('html') /* pos 7:3 */;
	}


	/** {block content} on line 9 */
	public function blockContent(array $ʟ_args): void
	{
		echo '  <div class="h-screen flex flex-col">
    <!-- ヘッダー -->
    <div class="p-6 text-center shadow">
      <h1 class="text-2xl font-bold">EPUB メタ情報入力</h1>
    </div>
    <!-- フォーム本体 -->
    <div class="w-full flex-1 flex items-center justify-center">
      <div id="epub-meta" class="w-[50%] space-y-4 p-6">
        <sl-input name="title" label="タイトル" placeholder="例：吾輩は猫である" required></sl-input>
        <sl-input name="creator" label="著者" placeholder="例：夏目漱石" required></sl-input>
        <sl-select name="language" label="言語" value="ja" required>
          <sl-option value="ja">日本語 (ja)</sl-option>
          <sl-option value="en">English (en)</sl-option>
        </sl-select>
        <sl-input name="publisher" label="発行元" placeholder="例：青空文庫"></sl-input>
        <sl-textarea name="description" label="説明" placeholder="この本の概要を入力してください..."></sl-textarea>
        <sl-button id="save-button" variant="primary" class="w-full">保存</sl-button>
      </div>
    </div>
  </div>
';
	}


	/** {block scripts} on line 31 */
	public function blockScripts(array $ʟ_args): void
	{
		echo '  <script type="module" src="/pages/js/entry.js"></script>
';
	}
}
