<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: pages/epub.latte */
final class Template_10740ac1d4 extends Latte\Runtime\Template
{
	public const Blocks = [
		['nav' => 'blockNav', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('nav', get_defined_vars()) /* pos 3:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 7:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/base.latte';
		return get_defined_vars();
	}


	/** {block nav} on line 3 */
	public function blockNav(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->createTemplate('../components/nav.latte', ['theme' => 'success'] + $this->params, 'include')->renderToContentType('html') /* pos 4:3 */;
	}


	/** {block content} on line 7 */
	public function blockContent(array $ʟ_args): void
	{
		echo '  <div id="viewer">
    <div id="zoom-wrapper"></div>
  </div>
';
	}
}
