<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: pages/image.latte */
final class Template_da86d7c2f2 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>Tech Book Editor</title>

<script src="https://cdn.jsdelivr.net/npm/markdown-it/dist/markdown-it.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jszip/dist/jszip.min.js"></script>
<script src="https://cdn.tailwindcss.com"></script>

<style>
html, body { height:100%; }
textarea { tab-size:2; }
.resize-handle{
  width:14px;height:14px;
  background:#2563eb;
  position:absolute;
  right:0;bottom:0;
  cursor:pointer;
}
</style>
</head>

<body class="h-full bg-gray-100 flex flex-col">

<!-- ================= TOOLBAR ================= -->
<div class="p-3 bg-white shadow flex gap-2 items-center">

  <button id="prevSection" class="px-3 py-1 bg-gray-200 rounded">&lt;</button>
  <button id="nextSection" class="px-3 py-1 bg-gray-200 rounded">&gt;</button>

  <button id="addSection" class="px-3 py-1 bg-green-500 text-white rounded">
    ＋ Section
  </button>

  <button id="addRight" class="px-3 py-1 bg-gray-200 rounded">
    右寄せ図
  </button>

  <button id="addLeft" class="px-3 py-1 bg-gray-200 rounded">
    左寄せ図
  </button>

  <button id="togglePreview" class="px-4 py-1 bg-blue-600 text-white rounded">
    Section Preview
  </button>

  <button id="exportEpub" class="px-4 py-1 bg-purple-600 text-white rounded">
    Export EPUB3
  </button>

  <span class="ml-auto text-sm text-gray-500">
    初期＝表紙
  </span>
</div>

<!-- ================= MAIN ================= -->
<div class="flex-1 overflow-hidden">

  <textarea id="editor"
    class="w-full h-full p-6 font-mono text-sm outline-none resize-none bg-white"></textarea>

  <div id="preview"
    class="hidden h-full overflow-auto p-10 bg-white prose max-w-none">
  </div>

</div>

<script>

/* ================= Markdown ================= */

const md = window.markdownit({ html:true });

function registerBlock(name){

  md.block.ruler.before("fence","custom_"+name,
    function(state,startLine,endLine,silent){

      let pos=state.bMarks[startLine]+state.tShift[startLine];
      let max=state.eMarks[startLine];
      let line=state.src.slice(pos,max).trim();

      const match=line.match(/^::: (.+) start(.*)$/);
      if(!match) return false;
      if(match[1]!==name) return false;
      if(silent) return true;

      const attr=match[2]||"";
      const sizeMatch=attr.match(/size="(sm|md|lg)"/);
      const size=sizeMatch?sizeMatch[1]:"md";

      let next=startLine+1;
      while(next<endLine){
        let p=state.bMarks[next]+state.tShift[next];
        let m=state.eMarks[next];
        let txt=state.src.slice(p,m).trim();
        if(txt===`::: ${name} end`) break;
        next++;
      }

      const open=state.push(name+"_open","",1);
      open.meta={size};
      state.md.block.tokenize(state,startLine+1,next);
      state.push(name+"_close","",-1);
      state.line=next+1;
      return true;
    });

  md.renderer.rules[name+"_open"]=(tokens,idx)=>{

    if(name==="cover"){
      return `<section class="hero text-center py-32 bg-gradient-to-r from-indigo-600 to-blue-500 text-white">
        <div class="max-w-3xl mx-auto">`;
    }

    if(name==="section"){
      return `<section class="my-16 clear-both">`;
    }

    if(name==="fig-right"||name==="fig-left"){

      const size=tokens[idx].meta.size;
      const widthClass={
        sm:"w-[25%]",
        md:"w-[35%]",
        lg:"w-[50%]"
      }[size];

      const floatClass=name==="fig-right"
        ? "float-right ml-6"
        : "float-left mr-6";

      return `<figure class="${floatClass} ${widthClass} mb-4 relative group">
        <div class="resize-handle"></div>`;
    }

    if(name==="container")
      return `<div class="flow-root my-6">`;

    return `<div>`;
  };

  md.renderer.rules[name+"_close"]=()=>{
    if(name==="cover") return `</div></section>`;
    if(name==="section") return `</section>`;
    if(name==="fig-right"||name==="fig-left") return `</figure>`;
    if(name==="container") return `</div>`;
    return `</div>`;
  };
}

registerBlock("cover");
registerBlock("section");
registerBlock("container");
registerBlock("fig-right");
registerBlock("fig-left");

/* ================= Section Data ================= */

let sections=[];
let currentIndex=0;

function saveCurrent(){
  sections[currentIndex]=editor.value;
}

function loadSection(){
  editor.value=sections[currentIndex]||"";
}

/* ================= Resize ================= */

function enableResize(){
  document.querySelectorAll("figure").forEach(fig=>{
    const handle=fig.querySelector(".resize-handle");
    if(!handle) return;

    handle.onclick=()=>{

      const sizes=["sm","md","lg"];
      const current=fig.className.includes("w-[25%]")?"sm":
                    fig.className.includes("w-[50%]")?"lg":"md";

      const next=sizes[(sizes.indexOf(current)+1)%3];

      editor.value=editor.value.replace(
        /size="(sm|md|lg)"/,
        `size="${next}"`
      );

      preview.innerHTML=md.render(editor.value);
      enableResize();
    };
  });
}

/* ================= Buttons ================= */

const editor=document.getElementById("editor");
const preview=document.getElementById("preview");

document.getElementById("togglePreview").onclick=()=>{
  saveCurrent();

  if(preview.classList.contains("hidden")){
    preview.innerHTML=md.render(editor.value);
    editor.classList.add("hidden");
    preview.classList.remove("hidden");
    enableResize();
  }else{
    preview.classList.add("hidden");
    editor.classList.remove("hidden");
  }
};

document.getElementById("prevSection").onclick=()=>{
  if(currentIndex>0){
    saveCurrent();
    currentIndex--;
    loadSection();
  }
};

document.getElementById("nextSection").onclick=()=>{
  if(currentIndex<sections.length-1){
    saveCurrent();
    currentIndex++;
    loadSection();
  }
};

document.getElementById("addSection").onclick=()=>{
  saveCurrent();
  sections.push(
`::: section start
# 見出し${sections.length}

本文

::: section end`
  );
  currentIndex=sections.length-1;
  loadSection();
};

function insertFigure(type){
  editor.value=editor.value.replace(
    "::: section end",
`::: container start

::: ${type} start size="md"
![画像](image.png)
::: ${type} end

::: container end

::: section end`
  );
}

document.getElementById("addRight").onclick=()=>insertFigure("fig-right");
document.getElementById("addLeft").onclick=()=>insertFigure("fig-left");

/* ================= EPUB Export ================= */

document.getElementById("exportEpub").onclick=async()=>{

  saveCurrent();

  const zip=new JSZip();

  zip.file("mimetype","application/epub+zip",{compression:"STORE"});

  zip.folder("META-INF")
     .file("container.xml",
`<?xml version="1.0"?>
<container version="1.0"
 xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
 <rootfiles>
  <rootfile full-path="OEBPS/content.opf"
   media-type="application/oebps-package+xml"/>
 </rootfiles>
</container>`);

  const OEBPS=zip.folder("OEBPS");

  const html=md.render(sections.join("\\n\\n"));

  OEBPS.file("content.xhtml",
`<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Book</title>
<link rel="stylesheet" type="text/css" href="book.css"/>
</head>
<body>
${html}
</body>
</html>`);

  OEBPS.file("book.css",
`body{font-family:serif;line-height:1.6;}
figure{margin:1em 0;}
`);

  OEBPS.file("nav.xhtml",
`<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
 xmlns:epub="http://www.idpf.org/2007/ops">
<head><title>TOC</title></head>
<body>
<nav epub:type="toc">
<ol>
<li><a href="content.xhtml">本文</a></li>
</ol>
</nav>
</body>
</html>`);

  OEBPS.file("content.opf",
`<?xml version="1.0" encoding="UTF-8"?>
<package version="3.0"
 xmlns="http://www.idpf.org/2007/opf"
 unique-identifier="bookid">
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
<dc:identifier id="bookid">bookid</dc:identifier>
<dc:title>Book</dc:title>
<dc:language>ja</dc:language>
</metadata>
<manifest>
<item id="content" href="content.xhtml"
 media-type="application/xhtml+xml"/>
<item id="nav" href="nav.xhtml"
 media-type="application/xhtml+xml"
 properties="nav"/>
<item id="css" href="book.css"
 media-type="text/css"/>
</manifest>
<spine>
<itemref idref="content"/>
</spine>
</package>`);

  const blob=await zip.generateAsync({type:"blob"});
  const a=document.createElement("a");
  a.href=URL.createObjectURL(blob);
  a.download="book.epub";
  a.click();
};

/* ================= 初期：表紙 ================= */

sections=[`::: section start

::: cover start
# タイトル
## サブタイトル

著者: 名前  
2026
::: cover end

::: section end`
];

loadSection();

</script>

</body>
</html>
';
	}
}
