<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: pages/epub.latte */
final class Template_fb3ab6a0a9 extends Latte\Runtime\Template
{
	public const Blocks = [
		['head' => 'blockHead', 'nav' => 'blockNav', 'content' => 'blockContent', 'scripts' => 'blockScripts'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('head', get_defined_vars()) /* pos 3:1 */;
		echo "\n";
		$this->renderBlock('nav', get_defined_vars()) /* pos 6:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 10:1 */;
		echo "\n";
		$this->renderBlock('scripts', get_defined_vars()) /* pos 16:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/base.latte';
		return get_defined_vars();
	}


	/** {block head} on line 3 */
	public function blockHead(array $ʟ_args): void
	{
	}


	/** {block nav} on line 6 */
	public function blockNav(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->createTemplate('../components/nav.latte', ['theme' => 'success'] + $this->params, 'include')->renderToContentType('html') /* pos 7:3 */;
	}


	/** {block content} on line 10 */
	public function blockContent(array $ʟ_args): void
	{
		echo '  <div id="viewer">
    <div id="zoom-wrapper"></div>
  </div>
';
	}


	/** {block scripts} on line 16 */
	public function blockScripts(array $ʟ_args): void
	{
		echo '<script type="module" src="/pages/epub/index.js"></script>
';
	}
}
